version: "3.8"
services:
  kopia:
    image: "randombytedeveloper/my-kopia:v0.7.2"
    environment:
      KOPIA_UI_USER: ${KOPIA_UI_USER}
      KOPIA_UI_PASS_SECRET_PATH: ${KOPIA_UI_PASS_SECRET_PATH}
      SOURCE_SERVER: ${SOURCE_SERVER}
      SOURCE_USER: ${SOURCE_USER}
      SOURCE_PASS_SECRET_PATH: ${SOURCE_PASS_SECRET_PATH}
    secrets:
      - KOPIA_UI_PASS
      - SOURCE_PASS
secrets:
  KOPIA_UI_PASS:
    external: true
  SOURCE_PASS:
    external: true
