# Docker compose v3 sadly doesn't support 'extends' and
# we can't define a common base between both targts

version: "3.8"
services:
  kopia:
    image: "randombytedeveloper/my-kopia:v0.9.2"
    ports:
      - "${PORT}:51515"
    # enables the container to mount SMB/CIFS share
    cap_add:
      - SYS_ADMIN
      - DAC_READ_SEARCH
    environment:
      KOPIA_UI_USER: ${KOPIA_UI_USER}
      KOPIA_UI_PASS_SECRET_PATH: ${KOPIA_UI_PASS_SECRET_PATH}
      SOURCE_SERVER: ${SOURCE_SERVER}
      SOURCE_USER: ${SOURCE_USER}
      SOURCE_PASS_SECRET_PATH: ${SOURCE_PASS_SECRET_PATH}
      B2_RECONNECT_TOKEN_SECRET_PATH: ${B2_RECONNECT_TOKEN_SECRET_PATH}
      MAX_UPLOAD_SPEED: ${MAX_UPLOAD_SPEED}
      MAX_DOWNLOAD_SPEED: ${MAX_DOWNLOAD_SPEED}
    secrets:
      - KOPIA_UI_PASS
      - SOURCE_PASS
      - B2_RECONNECT_TOKEN
secrets:
  KOPIA_UI_PASS:
    external: true
  SOURCE_PASS:
    external: true
  ${B2_RECONNECT_TOKEN_SECRET}:
    external: true
