version: "3.8"
services:
  scheduler:
    image: "randombytedeveloper/my-kopia-scheduler:v0.11.4"
    environment:
      CONTAINER_NAMES: ${CONTAINER_NAMES}
      COMMAND: ${COMMAND}
      SLEEP_INTERVAL: ${SLEEP_INTERVAL}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock