# Docker compose v3 sadly doesn't support 'extends' and
# we can't define a common base between both targts

version: "3.8"
services:
  kopia:
    image: "randombytedeveloper/my-kopia:v0.11.0"
    ports:
      - "${PORT}:51515"
    # enables the container to mount SMB/CIFS share
    cap_add:
      - SYS_ADMIN
      - DAC_READ_SEARCH
    environment:
      KOPIA_UI_USER: ${KOPIA_UI_USER}
      SOURCE_SERVER: ${SOURCE_SERVER}
      SOURCE_USER: ${SOURCE_USER}
      B2_BUCKET_NAME: ${B2_BUCKET_NAME}
      MAX_UPLOAD_SPEED: ${MAX_UPLOAD_SPEED}
      MAX_DOWNLOAD_SPEED: ${MAX_DOWNLOAD_SPEED}
    secrets:
      - KOPIA_UI_PASS
      - SOURCE_PASS
      - REPO_PASS
      - B2_KEY_ID
      - B2_KEY
secrets:
  KOPIA_UI_PASS:
    external: true
  SOURCE_PASS:
    external: true
  REPO_PASS:
    external: true
  B2_KEY_ID:
    external: true
  B2_KEY:
    external: true
