# Docker compose v3 sadly doesn't support 'extends' and
# we can't define a common base between both targts

version: "3.8"
services:
  kopia:
    image: "randombytedeveloper/my-kopia:v0.14.0"
    ports:
      - "${PORT}:51515"
    # enables the container to mount SMB/CIFS share
    cap_add:
      - SYS_ADMIN
      - DAC_READ_SEARCH
    environment:
      KOPIA_UI_USER: ${KOPIA_UI_USER}
      SOURCE_SERVER: ${SOURCE_SERVER}
      SOURCE_USER: ${SOURCE_USER}
      S3_ENDPOINT: ${S3_ENDPOINT}
      S3_BUCKET: ${B2_BUCKET}
      S3_ACCESS_KEY: ${S3_ACCESS_KEY}
    secrets:
      - KOPIA_UI_PASS
      - SOURCE_PASS
      - REPO_PASS
      - S3_SECRET_ACCESS_KEY
secrets:
  KOPIA_UI_PASS:
    external: true
  SOURCE_PASS:
    external: true
  REPO_PASS:
    external: true
  S3_SECRET_ACCESS_KEY:
    external: true
