name: Build and publish scheduler Docker images

on:
  release:
    types: [published]

jobs:
  build_and_push_kopia:
    uses: ./.github/workflows/build-and-push-image.yml
    with:
      image-name: randombytedeveloper/my-kopia-scheduler
      docker-file: ./scheduler/Dockerfile
    secrets: inherit
